version: '3.8'
services:
  ml_service:
    build: .
    volumes:
      - ./.cache:/cache
      - ./data:/data
      - ./src/:/src
    ports:
      - 8888:8888

    environment:
      - HF_DATASETS_CACHE=/cache

    command: [
      "jupyter", "lab",
      "--port=8888", "--ip=0.0.0.0",
      "--allow-root", "--browser=false", "--no-browser",
      "--IdentityProvider.token=''",
      "--ServerApp.password=''",
      "--allow_remote_access=true",
      "--NotebookApp.disable_check_xsrf=True",
    ]
    # command: ["jupyter", "lab", "--no-browser", "--allow-root", "--ip=0.0.0.0", "--port=8888"]
    # command: nvidia-smi
    # command: python3 ./src/hello.py

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
